// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LemonadeInheritProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("LemonadeInheritProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing LemonadeInheritProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LemonadeInheritProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "LemonadeInheritProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing LemonadeInheritProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
